# Generated by Django 3.2.9 on 2021-12-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('About', models.TextField()),
            ],
        ),
    ]
