# Generated by Django 3.2.9 on 2021-12-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='About',
            field=models.TextField(blank=True),
        ),
    ]
