# Generated by Django 3.2.9 on 2021-12-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room1', '0002_alter_biodata_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
